name: Verify that can be build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: CMake
        run: |
          mkdir build && cd build
          cmake ..
          cmake --build .
      - name: Upload bin file
        uses: actions/upload-artifact@v3
        with:
          name: unit-test
          path: ./build/tests/unit_test
          retention-days: 1

  unit-test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Download bin file
        uses: actions/download-artifact@v3
        with:
          name: unit-test

      - name: Test
        run: |
          chmod a+x ./unit_test
          ./unit_test
